[project]
name = "traffic-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.3",
    "stable-baselines3[extra]>=2.7.1",
    "sumo-rl>=1.4.5",
    "pettingzoo==1.24.3",
    "streamlit>=1.35.0",
    "plotly>=5.22.0",
    "pandas>=2.0.0",
    "folium>=0.20.0",
    "streamlit-folium>=0.27.2",
    "pyproj>=3.7.2",
]
